[package]
name = "cipher-paratime"
version = "2.4.0-testnet"
authors = ["Oasis Protocol Foundation <info@oasisprotocol.org>"]
edition = "2018"
license = "Apache-2.0"

[package.metadata.orc.release]
runtime-id = "000000000000000000000000000000000000000000000000e199119c992377cb"

[package.metadata.orc.test]
runtime-id = "0000000000000000000000000000000000000000000000000000000000000000"

[package.metadata.fortanix-sgx]
heap-size = 134217728
stack-size = 2097152
threads = 6
debug = false

[dependencies]
oasis-runtime-sdk = { git = "https://github.com/oasisprotocol/oasis-sdk", rev = "6bd5452f94cfabe59e6291bdc9ccf6426cb9d619" }
module-contracts = { git = "https://github.com/oasisprotocol/oasis-sdk", rev = "6bd5452f94cfabe59e6291bdc9ccf6426cb9d619", package = "oasis-runtime-sdk-contracts" }

# Third party.
once_cell = "1.8.0"
