[package]
name = "cipher-paratime"
version = "3.0.0-testnet"
authors = ["Oasis Protocol Foundation <info@oasisprotocol.org>"]
edition = "2021"
license = "Apache-2.0"

[package.metadata.orc.release]
runtime-id = "000000000000000000000000000000000000000000000000e199119c992377cb"

[package.metadata.orc.test]
runtime-id = "0000000000000000000000000000000000000000000000000000000000000000"

[package.metadata.fortanix-sgx]
heap-size = 268435456 # 256 MiB
stack-size = 2097152
threads = 8
debug = false

[dependencies]
keymanager = { git = "https://github.com/oasisprotocol/keymanager-paratime", tag = "v0.4.1-testnet" }

# SDK.
oasis-runtime-sdk = { git = "https://github.com/oasisprotocol/oasis-sdk", tag = "runtime-sdk/v0.8.1" }
module-contracts = { git = "https://github.com/oasisprotocol/oasis-sdk", tag = "runtime-sdk/v0.8.1", package = "oasis-runtime-sdk-contracts" }

# Third party.
once_cell = "1.8.0"
