# NOTE: This name appears in GitHub's Checks API and in workflow's status badge.
name: release

# Trigger the workflow when:
on:
  # A push occurs to one of the matched tags.
  push:
    tags:
      # Pattern that roughly matches Cipher ParaTime's version tags.
      # For more details on GitHub Actions' pattern match syntax, see:
      # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags.
      - 'v[0-9]+.[0-9]+*'

jobs:

  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go 1.17
        uses: actions/setup-go@v3
        with:
          go-version: "1.17.x"

      - name: Build tagged release, elf
        id: build-elf
        uses: oasisprotocol/oasis-sdk/.github/actions/hash-rust@main
        with:
          image: oasisprotocol/runtime-builder:main
          pkg-dirs: runtime,keymanager
          binaries: cipher-paratime,cipher-keymanager
          clean: no

      - name: Build tagged release, sgxs
        id: build-sgxs
        uses: oasisprotocol/oasis-sdk/.github/actions/hash-rust@main
        with:
          image: oasisprotocol/runtime-builder:main
          pkg-dirs: runtime,keymanager
          binaries: cipher-paratime.sgxs,cipher-keymanager.sgxs
          clean: no
          sgx: yes

      - name: Create the Oasis Runtime Containers
        run: |
          go install github.com/oasisprotocol/oasis-sdk/tools/orc@latest

          pushd runtime
          orc init ${RUNTIME_EXECUTABLE} --sgx-executable ${RUNTIME_SGXS} --output ../cipher-paratime.orc
          popd

          pushd keymanager
          orc init ${KEYMANAGER_EXECUTABLE} --sgx-executable ${KEYMANAGER_SGXS} --output ../cipher-keymanager.orc
          popd
        env:
          RUNTIME_EXECUTABLE: ${{ github.workspace }}/${{ steps.build-elf.outputs.build-path }}/cipher-paratime
          RUNTIME_SGXS: ${{ github.workspace }}/${{ steps.build-sgxs.outputs.build-path }}/cipher-paratime.sgxs

          KEYMANAGER_EXECUTABLE: ${{ github.workspace }}/${{ steps.build-elf.outputs.build-path }}/cipher-keymanager
          KEYMANAGER_SGXS: ${{ github.workspace }}/${{ steps.build-sgxs.outputs.build-path }}/cipher-keymanager.sgxs

      - name: Publish the release
        uses: ncipollo/release-action@v1
        with:
          # Create a draft since the release requires an offline signing process.
          draft: true
          artifacts: cipher-paratime.orc,cipher-keymanager.orc
          token: ${{ secrets.GITHUB_TOKEN }}
